### ISSUE TITLE
background color

### ISSUE THREAD

**Issue by Urkgrim** [yuyinws/steam-card#57]
the background color doesn't change

**Comment by yuyinws** [comment]
please provide your config URL.

**Comment by Urkgrim** [comment]
`<img width="400" height="140" src="https://card.yuy1n.io/card/76561197979154236/dark,en,badge,group,text-ffffff,bg-000000">`

**Comment by yuyinws** [comment]
> `<img width="400" height="140" src="https://card.yuy1n.io/card/76561197979154236/dark,en,badge,group,text-ffffff,bg-000000">`

doesn't it works? `bg-000000` is black.

![](https://card.yuy1n.io/card/76561197979154236/dark,en,badge,group,text-ffffff,bg-000000)

**Comment by Urkgrim** [comment]
nope for me this is the result:

![test](https://user-images.githubusercontent.com/65966112/206812074-c6b35e90-4f29-4a23-8583-4e75c4b7ca6a.jpg)

**Comment by yuyinws** [comment]
In my computer, it works normal:
<img width="555" alt="image" src="https://user-images.githubusercontent.com/38490578/206823136-ad711d6f-05ae-43cc-b69f-38c6465380cf.png">

It's very strange. I speculate that this may be caused by your browser extension or something.

You can try these way and observe whether it is normal:
1. Visit the config url on your phone.
(https://card.yuy1n.io/card/76561197979154236/dark,en,badge,group,text-ffffff,bg-000000)
2. Open the browser's `Incognito Window` and visit the config url.

**Comment by Urkgrim** [comment]
Currently im using Firefox, i tried another Browser now (Edge) and it worked. So it must be a browser specific problem. Are u planning to adapt it to Firefox?

**Comment by yuyinws** [comment]
This bug had been fixed. Thanks for your feedback!
